services:
  mysql:
    container_name: prestashop_db
    networks:
        - prestashop-network
    environment:
        - MYSQL_DATABASE=prestashop
        - MYSQL_USER=prestashop
        - MYSQL_PASSWORD=prestashop_password
        - MYSQL_ROOT_PASSWORD=prestashop_root
    volumes:
        - ./db_data:/var/lib/mysql
    image: mysql:8
    
  prestashop:
    networks:
        - prestashop-network
    environment:
        - PRESTASHOP_DB_SERVER=mysql
        - PRESTASHOP_DB_NAME=prestashop
        - PRESTASHOP_DB_USER=prestashop
        - PRESTASHOP_DB_PASSWORD=prestashop_password
    ports:
        - 8200:80
        - 8443:443
    volumes:
        - ./html:/var/www/html:delegated
    image: prestashop/prestashop:latest

networks:
  prestashop-network: